version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-image
    container_name: informacion-php
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    tty: true
    # command: ["composer", "install"]
    environment:
      SERVICE_NAME: healthyorchards
      SERVICE_TAGS: dev
    working_dir: /var/www

  


services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  www:
    image: nginx
    restart: always
    expose:
      - "81"
    volumes:
       - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    environment:
      - VIRTUAL_HOST=lainformacioncanuelas.com,www.lainformacioncanuelas.com


  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: informacion-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3307"
    environment:
      MYSQL_DATABASE: la_informacion_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql



  volumes: 
    certs:
    html:
    vhostd: